// Public name/taxonomy snapshot from https://antden.net/, 2026-09-30.
// Source IDs and merge decisions: docs/data/antden-species-import.json.
// Shared aliases are search candidates, never automatic identity mappings.
// No husbandry parameters or keeper records are imported.

const importedSpeciesOptions = <String, List<String>>{
  '芭切叶蚁': [
    'Atta robusta',
    '光滑芭切叶蚁',
    '六刺芭切叶蚁',
    '割草芭切叶蚁',
    '古巴芭切叶蚁',
    '哥伦比亚芭切叶蚁',
    '墨西哥芭切叶蚁',
    '岛屿芭切叶蚁',
    '巨首芭切叶蚁',
    '得州芭切叶蚁',
    '戈亚斯芭切叶蚁',
    '暗首芭切叶蚁',
    '沃伦魏德芭切叶蚁(直译)',
    '球形芭切叶蚁',
    '萨尔塔芭切叶蚁',
  ],
  '多刺蚁': [
    '三尖叉多刺蚁',
    '光胫多刺蚁',
    '半眼多刺蚁',
    '双钩多刺蚁',
    '叶形多刺蚁',
    '哈氏多刺蚁',
    '始兴多刺蚁',
    '平滑多刺蚁',
    '红腹多刺蚁',
    '结多刺蚁',
    '胡克多刺蚁',
    '阿玛多刺蚁',
    '阿玛多刺蚁 防御亚种',
  ],
  '弓背蚁': [
    '三色弓背蚁',
    '不等弓背蚁',
    '丛林弓背蚁',
    '丝毛弓背蚁',
    '丝腹弓背蚁',
    '乌头弓背蚁',
    '九州弓背蚁',
    '亮足弓背蚁',
    '任性弓背蚁',
    '伊宁弓背蚁',
    '伊氏弓背蚁',
    '伊东氏弓背蚁',
    '伦格弓背蚁',
    '佛州弓背蚁',
    '侧扁弓背蚁',
    '侧扁弓背蚁（指名亚种）',
    '傲慢弓背蚁',
    '光亮弓背蚁',
    '光弓背蚁',
    '光滑弓背蚁',
    '凯撒弓背蚁',
    '凯撒弓背蚁（帝王亚种）',
    '凹唇弓背蚁',
    '勤勉弓背蚁',
    '半褐弓背蚁',
    '南红弓背蚁',
    '卡林弓背蚁',
    '卡氏弓背蚁',
    '厚毛弓背蚁',
    '厚金弓背蚁',
    '古尔德弓背蚁',
    '台湾弓背蚁',
    '哀弓背蚁',
    '哈氏弓背蚁',
    '丝弓背蚁',
    '奇异弓背蚁',
    '奥特朗弓背蚁',
    '威尔曼弓背蚁',
    '威尔曼弓背蚁伽马亚种',
    '威尔曼弓背蚁红体亚种',
    '孔子弓背蚁',
    '安宁弓背蚁',
    '宾州弓背蚁',
    '宾氏弓背蚁',
    '少毛弓背蚁',
    '尼科巴弓背蚁山栖亚种',
    '巨头弓背蚁',
    '布鲁图斯弓背蚁',
    '平和弓背蚁',
    '平截弓背蚁',
    '广布弓背蚁萨哈林亚种',
    '庞培弓背蚁',
    '异色弓背蚁',
    '弗里德弓背蚁',
    '微亮弓背蚁',
    '微亮弓背蚁（指名亚种）',
    '微须弓背蚁',
    '怀特弓背蚁',
    '悲痛弓背蚁',
    '截胸弓背蚁',
    '扁头弓背蚁',
    '拟哀弓背蚁',
    '拟广布弓背蚁',
    '撒旦弓背蚁',
    '撒氏弓背蚁',
    '新几内亚弓背蚁',
    '新几内亚弓背蚁（矩头亚种）',
    '无畏弓背蚁',
    '无畏弓背蚁（指名亚种）',
    '无畏弓背蚁（好斗亚种）',
    '暗足弓背蚁',
    '杂色弓背蚁',
    '栗色弓背蚁',
    '欺诈弓背蚁',
    '毁木弓背蚁',
    '毕氏弓背蚁',
    '毛腹弓背蚁',
    '毛钳弓背蚁',
    '江华弓背蚁',
    '沙地弓背蚁',
    '沟齿弓背蚁',
    '洛厄里弓背蚁',
    '浅毛弓背蚁',
    '深黑弓背蚁',
    '混乱弓背蚁',
    '混杂弓背蚁',
    '满茸弓背蚁',
    '燃弓背蚁',
    '獒弓背蚁',
    '瑕疵弓背蚁',
    '田野弓背蚁',
    '白环弓背蚁',
    '百陶弓背蚁',
    '的威弓背蚁',
    '短柄弓背蚁',
    '短颈弓背蚁',
    '突厥弓背蚁',
    '索马里弓背蚁',
    '红头弓背蚁（红斑亚种）',
    '红弓背蚁',
    '红缘弓背蚁',
    '红股弓背蚁',
    '红足弓背蚁',
    '约翰克拉克弓背蚁',
    '纽约弓背蚁',
    '绢毛弓背蚁',
    '缺刺弓背蚁',
    '美丽弓背蚁',
    '美国弓背蚁',
    '羞怯弓背蚁',
    '脆弱弓背蚁',
    '膨胀弓背蚁',
    '艾提弓背蚁',
    '存储弓背蚁',
    '莱氏弓背蚁',
    '血斑弓背蚁',
    '褐毛弓背蚁',
    '褐红弓背蚁',
    '西姆森弓背蚁',
    '角弓背蚁',
    '谨慎弓背蚁',
    '贝氏弓背蚁',
    '费拉弓背蚁',
    '辐毛弓背蚁',
    '迅捷弓背蚁',
    '迅捷弓背蚁（伊内兹亚种）',
    '迅捷弓背蚁（勤奋亚种）',
    '迅捷弓背蚁（指名亚种）',
    '近须弓背蚁',
    '邦哈斯弓背蚁',
    '酋长弓背蚁',
    '里氏弓背蚁',
    '野蛮弓背蚁',
    '金毛弓背蚁',
    '金沙弓背蚁',
    '金环弓背蚁',
    '金腹弓背蚁',
    '铜毛弓背蚁',
    '锈色弓背蚁',
    '长头弓背蚁',
    '长毛弓背蚁',
    '阿育王弓背蚁',
    '多毛弓背蚁',
    '非凡弓背蚁',
    '鞍弓背蚁',
    '须弓背蚁',
    '人厌弓背蚁',
    '驼色弓背蚁',
    '黄头弓背蚁',
    '黄毛弓背蚁',
    '黄腹弓背蚁',
    '黑头弓背蚁',
    '黑角弓背蚁',
    '鼠弓背蚁',
    '丝腹弓背蚁（君王亚种）',
    '丝腹弓背蚁指名亚种',
    '凶猛弓背蚁',
    '四斑弓背蚁',
    '易怒弓背蚁',
    '满茸弓背蚁（指名亚种）',
    '满茸弓背蚁（本迪戈亚种）',
    '黄斑弓背蚁',
  ],
  '举腹蚁': [
    '上海举腹蚁',
    '亮胸举腹蚁',
    '凹唇举腹蚁',
    '双突柄举腹蚁',
    '台湾举腹蚁',
    '席氏举腹蚁',
    '柱头举腹蚁',
    '异化举腹蚁',
    '棕头举腹蚁',
    '比罗举腹蚁',
    '游举腹蚁',
    '煤黑举腹蚁',
    '玛氏举腹蚁',
    '粗纹举腹蚁',
  ],
  '大头蚁': [
    '上海大头蚁',
    '亮红大头蚁',
    '具单眼大头蚁',
    '凹大头蚁',
    '印大头蚁',
    '可爱大头蚁',
    '奇大头蚁',
    '对跖大头蚁',
    '广大头蚁',
    '康斯坦大头蚁',
    '异大头蚁',
    '杜氏大头蚁',
    '梅花山大头蚁',
    '沃森大头蚁',
    '淡黄大头蚁',
    '瑞亚大头蚁',
    '盖氏大头蚁',
    '矮大头蚁',
    '膨胀大头蚁',
    '莫氏大头蚁',
    '阿伦大头蚁',
  ],
  '光胸臭蚁': [
    '东方光胸臭蚁',
    '中华光胸臭蚁',
  ],
  '双节行军蚁': [
    '东方双节行军蚁',
    '光柄双节行军蚁',
    '古田山双节行军蚁',
    '台湾双节行军蚁',
    '富川双节行军蚁',
    '小双节行军蚁',
    '尤氏盲蚁',
    '拟齿突双节行军蚁',
    '武当山双节行军蚁',
    '沙克德双节行军蚁',
    '河南双节行军蚁',
    '泰国盲蚁',
    '爪哇双节行军蚁',
    '皮氏双节行军蚁',
    '窄足双节行军蚁',
    '粗角双节行军蚁',
    '菲律宾双节行军蚁',
    '西氏双节行军蚁',
    '诗琳通双节行军蚁',
    '赛奇双节行军蚁',
    '郑氏双节行军蚁',
    '锡兰双节行军蚁',
    '长结双节行军蚁',
    '霍氏双节行军蚁',
    '韦氏行军蚁（韦氏双节行军蚁）',
    '齿突双节行军蚁',
    '毕氏双节行军蚁（Aenictus bihamatus）',
    '毕氏双节行军蚁（Aenictus biroi）',
  ],
  '行军蚁': [
    '东方行军蚁',
    '乌头行军蚁',
    '亮褐行军蚁',
    '刺结行军蚁',
    '剑齿行军蚁',
    '威氏行军蚁',
    '山栖行军蚁',
    '微黄行军蚁',
    '梅氏行军蚁',
    '泰坦行军蚁',
    '泰坦行军蚁维氏亚种',
    '科氏行军蚁',
    '维希努行军蚁',
    '邻行军蚁',
    '黄色行军蚁',
    '非洲行军蚁',
    '黑色行军蚁',
  ],
  '毛蚁': [
    '东洋毛蚁',
    '中国毛蚁',
    '凹毛蚁',
    '加州毛蚁',
    '蚜居毛蚁',
    '遮盖毛蚁',
    '黄毛蚁',
  ],
  '林蚁': [
    '丝光灰褐蚁',
    '丝光褐林蚁',
    '中亚凹头蚁',
    '中华红林蚁',
    '乌拉尔蚁',
    '亮林蚁',
    '亮腹黑褐蚁',
    '光亮黑蚁',
    '光亮黑蚁台湾亚种',
    '光滑背蚁',
    '多栉蚁',
    '掘穴蚁',
    '格劳卡蚁',
    '毛林蚁',
    '毛柄草地蚁',
    '毛眼林蚁',
    '灰褐蚁',
    '石狩红蚁',
    '叶盛山蚁',
    '红褐林蚁',
    '草原蚁',
    '血红林蚁',
  ],
  '小家蚁': [
    '中华小家蚁',
    '法老小家蚁',
    '破坏单家蚁',
    '花居小家蚁',
    '黑腹小家蚁',
    '勤劳小家蚁',
  ],
  '曲颊猛蚁': [
    '中华曲颊蚁',
    '宾氏曲颊猛蚁',
    '熊猫曲颊猛蚁',
  ],
  '短猛蚁': [
    '中华短猛蚁',
    '短背短猛蚁',
    '马拉维短猛蚁',
    '黄短猛蚁',
    '黄足短猛蚁',
    '黑色短猛蚁',
  ],
  '猛蚁': [
    '中华细颚猛蚁',
    '争吵大齿猛蚁',
    '二齿猛蚁',
    '五齿猛蚁',
    '光亮大齿猛蚁',
    '单穴扁胸猛蚁',
    '句芒大齒猛蟻',
    '基氏细猛蚁',
    '孔子细颚猛蚁',
    '安南扁头猛蚁',
    '宾氏细颚猛蚁',
    '巨首大齿猛蚁',
    '广西猛蚁',
    '蓝双刺猛蚁',
    '敏捷扁头猛蚁',
    '方结凹猛蚁',
    '爪哇扁头猛蚁',
    '片突扁头猛蚁',
    '片马猛蚁',
    '神农猛蚁',
    '穴居大齿猛蚁',
    '粒纹大齿猛蚁',
    '紫青双刺猛蚁',
    '缅甸细颚猛蚁',
    '高大齿猛蚁',
    '蓝链细颚猛蚁',
    '蓬莱大齿猛蚁',
    '西氏大齿猛蚁',
    '邵氏扁头猛蚁',
    '郑氏扁头猛蚁',
  ],
  '酸臭蚁': [
    '中华酸臭蚁',
    '黑头酸臭蚁',
  ],
  '影蚁': [
    '中国影蚁',
  ],
  '伪切叶蚁': [
    '中红伪切叶蚁',
    '亮红伪切叶蚁',
    '贝卡伪切叶蚁',
  ],
  '收获蚁': [
    '中红收获蚁',
    '乌檀收获蚁',
    '亚历山大收获蚁',
    '亚细结收获蚁',
    '亮角蚁',
    '伊比利亚收获蚁',
    '切齿收获蚁',
    '半红收获蚁',
    '单色收获蚁',
    '南方收获蚁',
    '喜马拉雅收获蚁',
    '埃及收获蚁',
    '多变收获蚁',
    '好望角收获蚁',
    '婀娜收获蚁',
    '小收获蚁',
    '截收获蚁',
    '摩洛哥收获蚁',
    '无刺收获蚁',
    '条纹收获蚁',
    '野蛮收获蚁桑氏亚种',
    '沃氏收获蚁',
    '沙地收获蚁',
    '没食子收获蚁',
    '热带收获蚁',
    '牛头收获蚁',
    '牧氏收获蚁',
    '王者收获蚁',
    '着色收获蚁',
    '砖红收获蚁',
    '移动收获蚁',
    '立毛收获蚁',
    '粗节收获蚁',
    '红褐收获蚁',
    '纯洁收获蚁',
    '纹额收获蚁',
    '葡萄牙收获蚁',
    '角收获蚁',
    '费氏收获蚁',
    '躁动收获蚁',
    '迷惑收获蚁',
    '邻近收获蚁',
    '野蛮收获蚁（五倍子亚种）',
    '须收获蚁',
    '麦氏收获蚁',
    '黑海收获蚁',
    '齿节收获蚁',
    '微颚齿收获蚁',
  ],
  '蜜罐蚁': [
    '乌黑蜜罐蚁',
    '克氏蜜罐蚁',
    '尤马蜜罐蚁',
    '平眼蜜罐蚁',
    '拟态蜜罐蚁',
    '科尔蜜罐蚁',
    '肯氏蜜罐蚁',
    '谎言蜜罐蚁',
  ],
  '海胆蚁': [
    '乞拉朋海胆蚁',
  ],
  '箭蚁': [
    '二色箭蚁',
    '亮红箭蚁',
    '宽节箭蚁',
    '淡色箭蚁',
    '疾行箭蚁',
    '艾箭蚁',
    '迅捷箭蚁',
  ],
  '火蚁': [
    '五刺火蚁',
    '入侵红火蚁',
    '巨工火蚁',
    '急逃火蚁',
    '截火蚁',
    '敌火蚁',
    '棉火蚁',
    '热带火蚁',
    '琥珀火蚁',
    '知本火蚁',
    '苏州火蚁',
    '贾氏火蚁',
    '金属火蚁',
    '黑火蚁',
  ],
  '盗蚁': [
    '亚光盗蚁',
  ],
  '平头蚁': [
    '亮平头蚁',
    '台湾平头蚁',
    '小体平头蚁',
    '栗红平头蚁',
    '爆炸平头蚁',
    '来氏平头蚁',
  ],
  '臭蚁': [
    '亮毛凹头臭蚁',
    '塔氏臭蚁',
    '西伯利亚臭蚁',
    '邻臭蚁',
  ],
  '盘腹蚁': [
    '伊比利亚盘腹蚁',
    '包公盘腹蚁',
    '地栖盘腹蚁',
    '大吉盘腹蚁',
    '大眼盘腹蚁',
    '家盘腹蚁',
    '小刺盘腹蚁',
    '日本盘腹蚁',
    '玄天盘腹蚁',
    '白毛盘腹蚁',
    '美西盘腹蚁',
    '贝卡盘腹蚁',
    '费氏盘腹蚁',
    '长头盘腹蚁',
    '隆胸盘腹蚁',
    '雕刻盘腹蚁',
    '高桥盘腹蚁',
  ],
  '卷尾猛蚁': [
    '伊藤卷尾猛蚁',
    '克平卷尾猛蚁',
  ],
  '顶切叶蚁': [
    '伦氏顶切叶蚁',
    '八刺顶切叶蚁',
    '圆盘顶切叶蚁',
    '变色顶切叶蚁',
    '冠顶切叶蚁',
    '罗格斯顶切叶蚁',
  ],
  '恐猛蚁': [
    '光亮恐猛蚁',
    '巨人恐猛蚁',
    '方头恐猛蚁',
    '长足恐猛蚁',
  ],
  '牛蚁': [
    '光亮牛蚁',
    '剑齿牛蚁',
    '小异牛蚁',
    '哈氏牛蚁',
    '多毛牛蚁',
    '娇美牛蚁',
    '巨首牛蚁',
    '显贵牛蚁',
    '火山牛蚁',
    '燃烧牛蚁',
    '短结牛蚁',
    '美丽牛蚁',
    '褐臀牛蚁',
    '褐足牛蚁',
    '贪食牛蚁',
    '迷走牛蚁',
    '饕餮牛蚁',
    '黄尾牛蚁',
    '黄跗牛蚁',
    '黑头牛蚁',
    '黑带牛蚁',
    '黑柄牛蚁',
    '梨形牛蚁',
    'SP17牛蚁（未定种）',
  ],
  '盾胸切叶蚁': [
    '光滑盾胸切叶蚁',
    '毛盾胸切叶蚁',
    '细刻瘤胸切叶蚁',
  ],
  '棘颚蚁': [
    '光腹棘颚蚁',
    '眼棘颚蚁',
    '短角棘颚蚁',
  ],
  '刺切叶蚁': [
    '光腿刺切叶蚁',
    '厚背刺家蟻',
  ],
  '铺道蚁': [
    '光颚铺道蚁',
    '凶暴铺道蚁',
    '多型铺道蚁',
    '广西铺道蚁',
    '弗氏铺道蚁',
    '日本铺道蚁',
    '津岛铺道蚁',
    '相似铺道蚁',
    '罗氏铺道蚁',
    '茸毛铺道蚁',
    '陕西铺道蚁',
    '食客铺道蚁',
  ],
  '巨首蚁': [
    '全异盲切叶蚁菲律宾亚种',
    '原子盲切叶蚁',
    '增城盲切叶蚁',
    '布氏盲切叶蚁',
    '木盲切叶蚁',
    '栗色盲切叶蚁',
    '老挝盲切叶蚁',
    '近缘盲切叶蚁',
    '邵氏寡家蟻',
    '非洲贼蚁',
    '高结盲切叶蚁',
    '黑沟盲切叶蚁',
    '龙盲切叶蚁',
  ],
  '卵角蚁': [
    '八节卵角蚁',
    '毕氏卵角蚁',
  ],
  '尖尾蚁': [
    '八重山尖尾蚁',
    '布氏尖尾蚁',
    '日本尖尾蚁',
    '海洋尖尾蚁',
    '灵动尖尾蚁',
    '邵氏尖尾蚁',
    '雨师尖尾蚁',
  ],
  '云蚁': [
    '六刺云行军蚁',
  ],
  '瘤颚蚁': [
    '六节瘤颚蚁',
    '刘氏瘤颚蚁',
    '长瘤颚蚁',
    '隈取瘤颚蚁',
    '高作瘤颚蚁',
  ],
  '僵蚁': [
    '冠角僵蚁',
  ],
  '狡臭蚁': [
    '冥府臭蚁',
    '白足狡臭蚁',
    '莫氏狡臭蚁',
  ],
  '离猛蚁': [
    '冥界离猛蚁',
  ],
  '细长蚁': [
    '凹唇细长蚁',
    '埃塞俄比亚细长蚁',
    '尖细长蚁',
    '巨眼细长蚁',
    '异细长蚁',
    '无缘细长蚁',
    '显赫细长蚁',
    '榕细长蚁',
    '牛眼细长蚁',
    '狭唇细长蚁',
    '飘细长蚁',
  ],
  '棱胸切叶蚁': [
    '刻纹棱胸切叶蚁',
    '短刺棱胸切叶蚁',
  ],
  '新猛蚁': [
    '剑颚新猛蚁',
  ],
  '梳猛蚁': [
    '剑齿梳猛蚁',
  ],
  '须蚁': [
    '加州须蚁',
    '双色须蚁',
    '安沙须蚁',
    '寄生须蚁',
    '异色罗纹须蚁',
    '穴须蚁',
    '栗红须蚁',
    '细刺须蚁',
    '罗纹须蚁',
    '马里科帕须蚁',
  ],
  '原细蚁': [
    '北京原细蚁',
    '叉颚原细蚁',
    '林氏原細蟻',
  ],
  '细蚁': [
    '北京细蚁',
    '沃达细蚁（伏地魔细蚁）',
  ],
  '原蚁': [
    '华丽原蚁',
    '棱原蚁',
    '草原原蚁',
    '贾氏原蚁',
  ],
  '粗颚猛蚁': [
    '南非粗颚猛蚁',
    '皮氏粗颚猛蚁',
  ],
  '无齿猛蚁': [
    '卡氏无齿猛蚁',
    '邵氏无齿猛蚁',
  ],
  '背门蚁': [
    '卡拉齐背门蚁',
  ],
  '迷猛蚁': [
    '卡米拉迷猛蚁',
    '显唇迷猛蚁',
  ],
  '游蚁': [
    '厚甲游蚁',
    '布氏游蚁',
    '贪婪游蚁',
    '钩齿游蚁',
  ],
  '修猛蚁': [
    '双刺修猛蚁',
    '红足修猛蚁',
  ],
  '丝切叶蚁': [
    '可爱丝切叶蚁',
  ],
  '隐猛蚁': [
    '臺灣隱針蟻',
    '拟大隐猛蚁',
    '邵氏隐猛蚁',
  ],
  '红蚁': [
    '吉市红蚁',
    '弯角红蚁',
    '米芾红蚁',
  ],
  '切胸蚁': [
    '和谐切胸蚁',
    '木野村切胸蚁',
    '疑切胸蚁',
    '近缘切胸蚁',
  ],
  '漫蚁': [
    '哈氏漫蚁',
    '艾氏漫蚁',
  ],
  '后蚁': [
    '善义后蚁',
  ],
  '锯猛蚁': [
    '埃塞俄比亚锯猛蚁',
  ],
  '扁胸切叶蚁': [
    '埃氏扁胸切叶蚁',
  ],
  '龟蚁': [
    '分化龟蚁',
    '小龟蚁',
    '盾龟蚁',
    '黑盾龟蚁',
    '黑衣龟蚁',
  ],
  '翼切叶蚁': [
    '多毛翼切叶蚁',
  ],
  '无结猛蚁': [
    '大眼无结猛蚁',
  ],
  '脊蚁': [
    '大眼脊蚁',
  ],
  '双凸切叶蚁': [
    '夫氏双凸切叶蚁',
  ],
  '棒角蚁': [
    '媽祖粗跗家蟻',
  ],
  '角蚁': [
    '孤角窝蚁',
  ],
  '捷蚁': [
    '守卫捷蚁',
    '长足捷蚁',
  ],
  '真收获蚁': [
    '安氏真收获蚁',
  ],
  '钩猛蚁': [
    '小眼钩猛蚁',
    '格拉夫钩猛蚁',
    '洞居盲细钩猛蚁',
    '混杂钩猛蚁',
    '粗糙钩猛蚁',
    '里氏钩猛蚁',
    '马达拉钩猛蚁',
  ],
  '麻臭蚁': [
    '小麻臭蚁',
  ],
  '火星蚁': [
    '尤里卡火星蚁',
  ],
  '恐蚁': [
    '巨人恐蚁',
    '巨人恐蚁（婆罗洲亚种）',
  ],
  '犰蚁': [
    '巨犰蚁',
  ],
  '巨猛蚁': [
    '黄臀巨猛蚁',
  ],
  '祖切叶蚁': [
    '布氏祖切叶蚁',
    '条纹祖切叶蚁',
    '西氏祖切叶蚁',
  ],
  '颀蚁': [
    '希颀蚁',
  ],
  '高黎贡山蚁': [
    '平背高黎贡蚁',
  ],
  '微猛蚁': [
    '弗雷氏蜂蚁',
  ],
  '中猛蚁': [
    '拟黑中猛蚁',
  ],
  '悍蚁': [
    '斗士悍蚁',
    '橘红悍蚁',
  ],
  '俄蚁': [
    '方结俄蚁',
  ],
  '姬猛蚁': [
    '日本姬猛蚁',
    '邵氏姬針蟻',
  ],
  '内瓦蚁': [
    '暗胸内瓦蚁',
  ],
  '点猛蚁': [
    '木兰点猛蚁',
    '褐红点猛蚁',
    '西氏点猛蚁',
    '贝利点猛蚁',
  ],
  '润蚁': [
    '格氏润蚁',
  ],
  '克雷蚁': [
    '棱纹克雷蚁',
  ],
  '粗角蚁': [
    '槽结粗角蚁',
  ],
  '拟立毛蚁': [
    '樱花拟立毛蚁',
  ],
  '毒针蚁': [
    '武装毒针蚁',
  ],
  '钝猛蚁': [
    '毛柄钝猛蚁',
    '米氏钝猛蚁',
    '长颚钝猛蚁',
  ],
  '拟毛蚁': [
    '污黄拟毛蚁',
    '相似拟光蚁',
  ],
  '斜结蚁': [
    '满斜结蚁',
    '阿禄斜结蚁',
    '龙王斜结蚁',
  ],
  '心结蚁': [
    '灰黑心结蚁',
    '裸心结蚁',
  ],
  '镰猛蚁': [
    '猎镰猛蚁',
    '跳镰猛蚁',
  ],
  '圆颚蚁': [
    '瘤点圆颚蚁',
  ],
  '新收获蚁': [
    '白毛新收获蚁',
    '科氏新收获蚁',
  ],
  '厚结猛蚁': [
    '短柄厚结蚁',
    '粗结厚结猛蚁',
  ],
  '巨眼蚁': [
    '破坏巨眼蚁',
  ],
  '钳蚁': [
    '笼罩钳蚁',
  ],
  '沟切叶蚁': [
    '粒沟切叶蚁',
  ],
  '狂蚁': [
    '红狂蚁',
  ],
  '矛猛蚁': [
    '红矛猛蚁',
  ],
  '虹臭蚁': [
    '红黑虹臭蚁',
    '维多利亚虹臭蚁',
    '蓝彩虹臭蚁',
    '血色虹臭蚁',
    '铜绿虹臭蚁',
  ],
  '异形蚁': [
    '翁萼豆异形蚁',
    '莫氏异形蚁',
  ],
  '脊红蚁': [
    '褐色脊红蚁',
  ],
  '原臭蚁': [
    '西蒙原臭蚁',
  ],
  '短角蚁': [
    '豪氏短角蚁',
  ],
  '中盲猛蚁': [
    '费氏中盲猛蚁',
  ],
  '匿猛蚁': [
    '迟钝匿猛蚁',
  ],
  '股猛蚁': [
    '逢股猛蚁',
  ],
  '异节蚁': [
    '金刻异节蚁',
  ],
  '华丽蚁': [
    '锡兰华丽蚁',
  ],
  '小盲猛蚁': [
    '长柄小盲猛蚁',
  ],
  '织叶蚁': [
    '长结织叶蚁',
  ],
  '立毛蚁': [
    '长角立毛蚁',
  ],
  '拟芭切叶蚁': [
    '阿根廷拟芭切叶蚁',
  ],
  '穴细蚁': [
    '雄王穴细蚁',
  ],
  '真结蚁': [
    '高真结蚁',
  ],
  '尼氏蚁': [
    '黄足尼氏蚁',
  ],
  '枪盾猛蚁': [
    '齿跗枪盾猛蚁',
  ],
  '真猛蚁': [
    '多毛真猛蚁（Euponera pilosior）',
  ],
  '费猛蚁': [
    '多毛真猛蚁（Fisheropone pilosior）',
  ],
  '响蚁': [
    '大眼响蚁',
  ],
  '长齿蚁': [
    '宾氏长齿蚁',
  ],
  '凹臭蚁': [
    '无毛凹臭蚁',
  ],
  '短蚁': [
    '无毛短蚁',
  ],
};

const importedSpeciesSearchAliases = <String, List<String>>{
  '肩角弓背蚁': [
    '丝腹弓背蚁指名亚种',
    '丝腹弓背蚁（君王亚种）',
  ],
  '易怒弓背蚁': [
    '凶猛弓背蚁',
    '易怒弓背蚁',
  ],
  '拟黑多刺蚁': [
    '双齿多刺蚁',
    '拟黑多刺蚁',
  ],
  '黄斑弓背蚁': [
    '四斑弓背蚁',
    '黄斑弓背蚁',
  ],
  '多毛真猛蚁': [
    '多毛真猛蚁（Euponera pilosior）',
    '多毛真猛蚁（Fisheropone pilosior）',
  ],
  '无颚齿收获蚁': [
    '微颚齿收获蚁',
    '无颚齿收获蚁',
  ],
  '无毛凹臭蚁': [
    '无毛凹臭蚁',
    '无毛短蚁',
  ],
  '毕氏双节行军蚁': [
    '毕氏双节行军蚁（Aenictus bihamatus）',
    '毕氏双节行军蚁（Aenictus biroi）',
  ],
  '满绒弓背蚁': [
    '满茸弓背蚁（指名亚种）',
    '满茸弓背蚁（本迪戈亚种）',
  ],
  '黑色行军蚁': [
    '非洲行军蚁',
    '黑色行军蚁',
  ],
};

const importedSpeciesAliases = <String, String>{
  'SP17牛蚁': 'SP17牛蚁（未定种）',
  'Myrmecia sp.17': 'SP17牛蚁（未定种）',
  'Polyrhachis thrinax': '三尖叉多刺蚁',
  '血红多刺蚁': '三尖叉多刺蚁',
  'Camponotus tricoloratus': '三色弓背蚁',
  'Crematogaster zoceensis': '上海举腹蚁',
  'pheidole zoceana': '上海大头蚁',
  'Camponotus inaequalis': '不等弓背蚁',
  'Camponotus dumetorum': '丛林弓背蚁',
  'Liometopum orientale': '东方光胸臭蚁',
  'Aenictus orientalis': '东方双节行军蚁',
  'Messor orientalis': '东方收获蚁',
  'Dorylus orientalis': '东方行军蚁',
  'Lasius nipponensis': '东洋毛蚁',
  'Formica fuscocinerea': '丝光灰褐蚁',
  'Formica fusca': '丝光褐林蚁',
  'Camponotus holosericeus': '丝毛弓背蚁',
  '中华弓背蚁': '丝毛弓背蚁',
  'Camponotus sericeiventris': '丝腹弓背蚁',
  'Camponotus sericeiventris rex': '丝腹弓背蚁（君王亚种）',
  'Camponotus sericeiventris sericeiventris': '丝腹弓背蚁指名亚种',
  'Formica mesasiatica': '中亚凹头蚁',
  '中亚弓背蚁': '全黄土耳其弓背蚁',
  'Camponotus turkestanus': '全黄土耳其弓背蚁',
  '全黄弓背蚁': '全黄土耳其弓背蚁',
  'Liometopum sinense': '中华光胸臭蚁',
  'Pheidole sinica': '中华大头蚁',
  '中华四节大头蚁': '中华大头蚁',
  'Monomorium chinense': '中华小家蚁',
  'Gnamptogenys chinensis': '中华曲颊蚁',
  'Brachyponera chinensis': '中华短猛蚁',
  'Formica sinensis': '中华红林蚁',
  'Leptogenys chinensis': '中华细颚猛蚁',
  'Tapinoma sinense': '中华酸臭蚁',
  'Syscia chinensis': '中国影蚁',
  '中华影蚁': '中国影蚁',
  'Lasius chinensis': '中国毛蚁',
  'Pseudomyrmex rufomedius': '中红伪切叶蚁',
  'Messor medioruber': '中红收获蚁',
  'Camponotus atriceps': '乌头弓背蚁',
  'Dorylus atriceps': '乌头行军蚁',
  'Formica uralensis': '乌拉尔蚁',
  'Messor ebeninus': '乌檀收获蚁',
  'Myrmecocystus melanoticus': '乌黑蜜罐蚁',
  'Camponotus kiusiuensis': '九州弓背蚁',
  'Echinopla cherapunjiensis': '乞拉朋海胆蚁',
  'Odontomachus rixosus': '争吵大齿猛蚁',
  'Meranoplus bicolor': '二色盾胸切叶蚁',
  '萌盾': '二色盾胸切叶蚁',
  'Cataglyphis bicolor': '二色箭蚁',
  'Ponera diodonta': '二齿猛蚁',
  'Solenopsis quinquecuspis': '五刺火蚁',
  'Ponera pentodontos': '五齿猛蚁',
  'Harpagoxenus sublaevis': '亚光盗蚁',
  'Messor alexandri': '亚历山大收获蚁',
  'Messor subgracilinodis': '亚细结收获蚁',
  'Colobopsis vitreus': '亮平头蚁',
  'Formica clara': '亮林蚁',
  'Dolichoderus pilinomas': '亮毛凹头臭蚁',
  'Lasius fuliginosus': '亮毛蚁',
  'Pseudomyrmex fervidus': '亮红伪切叶蚁',
  '刺槐共生蚁': '亮红伪切叶蚁',
  'Pheidole fervida': '亮红大头蚁',
  'Cataglyphis rubra': '亮红箭蚁',
  'Crematogaster egidyi': '亮胸举腹蚁',
  'Formica gagatoides': '亮腹黑褐蚁',
  'Dorylus laevigatus': '亮褐行军蚁',
  'Messor antennatus': '亮角蚁',
  '北非收获蚁': '亮角蚁',
  '触角收获蚁': '亮角蚁',
  'Camponotus claripes': '亮足弓背蚁',
  'Camponotus morosus': '任性弓背蚁',
  'Pheidole yeensis': '伊大头蚁',
  'Camponotus yiningensis': '伊宁弓背蚁',
  'Messor ibericus': '伊比利亚收获蚁',
  'Aphaenogaster iberica': '伊比利亚盘腹蚁',
  'Camponotus eastwoodi': '伊氏弓背蚁',
  '东木弓背蚁': '伊氏弓背蚁',
  '伊斯特伍德弓背蚁': '伊氏弓背蚁',
  'Proceratium itoi': '伊藤卷尾猛蚁',
  'Camponotus itoi': '伊东氏弓背蚁',
  'Camponotus renggeri': '伦格弓背蚁',
  'Acromyrmex lundii': '伦氏顶切叶蚁',
  'Camponotus floridanus': '佛州弓背蚁',
  'Camponotus compressus': '侧扁弓背蚁',
  '印度厕所蚁': '侧扁弓背蚁',
  'Camponotus compressus compressus': '侧扁弓背蚁（指名亚种）',
  'Camponotus arrogans': '傲慢弓背蚁',
  'Odontomachus fulgidus': '光亮大齿猛蚁',
  'Camponotus clarior': '光亮弓背蚁',
  'Dinoponera lucida': '光亮恐猛蚁',
  'Myrmecia fulgida': '光亮牛蚁',
  '金尾牛蚁': '光亮牛蚁',
  'Formica candida': '光亮黑蚁',
  '高加索黑蚁': '光亮黑蚁',
  'Formica candida formosae': '光亮黑蚁台湾亚种',
  'Camponotus politae': '光弓背蚁',
  '光洁弓背蚁': '光弓背蚁',
  'Aenictus laeviceps': '光柄双节行军蚁',
  'Camponotus laevigatus': '光滑弓背蚁',
  'Meranoplus laeviventris': '光滑盾胸切叶蚁',
  'Formica glabridorsis': '光滑背蚁',
  '格莱多蚁': '光滑背蚁',
  'Atta laevigata': '光滑芭切叶蚁',
  'Polyrhachis tibialis': '光胫多刺蚁',
  'Acanthognathus laevigatus': '光腹棘颚蚁',
  'Acanthomyrmex glabfemoralis': '光腿刺切叶蚁',
  'Tetramorium insolens': '光颚铺道蚁',
  'Proceratium kepingmai': '克平卷尾猛蚁',
  'Myrmecocystus creightoni': '克氏蜜罐蚁',
  'Solenopsis invicta': '入侵红火蚁',
  '无敌火蚁': '入侵红火蚁',
  '红火蚁': '入侵红火蚁',
  'Carebara diversa philippina': '全异盲切叶蚁菲律宾亚种',
  '全异盲切叶蚁': '全异巨首蚁',
  'Carebara diversa': '全异巨首蚁',
  '全异拟大头家蚁': '全异巨首蚁',
  '多样寡家蚁': '全异巨首蚁',
  'Acromyrmex octospinosus': '八刺顶切叶蚁',
  'Ooceraea octoantenna': '八节卵角蚁',
  'Acropyga yaeyamensis': '八重山尖尾蚁',
  'Yunodorylus sexspinus': '六刺云行军蚁',
  'Atta sexdens': '六刺芭切叶蚁',
  'Strumigenys hexamera': '六节瘤颚蚁',
  'Pheidole ocellata': '具单眼大头蚁',
  'Ankylomyrma coronacantha': '冠角僵蚁',
  'Technomyrmex hades': '冥府臭蚁',
  'Apomyrma stygia': '冥界离猛蚁',
  'Camponotus caesar': '凯撒弓背蚁',
  'Camponotus caesar imperator': '凯撒弓背蚁（帝王亚种）',
  'Tetramorium ferox': '凶暴铺道蚁',
  'Camponotus rapax': '凶猛弓背蚁',
  '敏感弓背蚁': '凶猛弓背蚁',
  'Crematogaster concavoclypeus': '凹唇举腹蚁',
  'Camponotus dorex': '凹唇弓背蚁',
  'Tetraponera concava': '凹唇细长蚁',
  'Pheidole sulcaticeps': '凹大头蚁',
  'Lasius emarginatus': '凹毛蚁',
  'Messor incisus': '切齿收获蚁',
  '列氏扁头猛蚁': '扁头猛蚁',
  'Ectomomyrmex lecuvenchocki': '扁头猛蚁',
  'Strumigenys S. lewisi': '刘氏瘤颚蚁',
  'Dorylus spininodis': '刺结行军蚁',
  'Pristomyrmex punctatus': '刻纹棱胸切叶蚁',
  'Neoponera rostrata': '剑颚新猛蚁',
  'Plectroctena mandibularis': '剑齿梳猛蚁',
  'Myrmecia mandibularis': '剑齿牛蚁',
  'Dorylus mandibularis': '剑齿行军蚁',
  'Atta capiguara': '割草芭切叶蚁',
  'Lasius californicus': '加州毛蚁',
  'Pogonomyrmex californicus': '加州须蚁',
  'Messor laboriosus': '勤劳收获蚁',
  'Camponotus sedulus': '勤勉弓背蚁',
  'Aphaenogaster baogong': '包公盘腹蚁',
  'Protanilla beijingensis': '北京原细蚁',
  'Leptanilla beijingensis': '北京细蚁',
  'Polyrhachis pubescens': '半眼多刺蚁',
  'Messor semirufus': '半红收获蚁',
  'Camponotus semitestaceus': '半褐弓背蚁',
  '砖红弓背蚁': '半褐弓背蚁',
  'Proformica splendida': '华丽原蚁',
  'Ectomomyrmex unicolor': '单穴扁胸猛蚁',
  'Messor concolor': '单色收获蚁',
  'Messor meridionalis': '南方收获蚁',
  'Camponotus CA02': '南红弓背蚁',
  'Streblognathus aethiopicus': '南非粗颚猛蚁',
  '争吵纹胸猛蚁': '南非粗颚猛蚁',
  'Camponotus carin': '卡林弓背蚁',
  'Camponotus cameroni': '卡氏弓背蚁',
  'Discothyrea kamiteta': '卡氏无齿猛蚁',
  'Notostigma carazzii': '卡拉齐背门蚁',
  'Mystrium camillae': '卡米拉迷猛蚁',
  'Pheidole indica': '印大头蚁',
  'Camponotus monju': '厚毛弓背蚁',
  'Eciton quadriglume': '厚甲游蚁',
  'Acanthomyrmex crassispinus': '厚背刺家蟻',
  '厚背刺蚁': '厚背刺家蟻',
  'Camponotus fulvopilosus': '厚金弓背蚁',
  'Carebara atoma': '原子盲切叶蚁',
  'Protanilla furcomandibula': '叉颚原细蚁',
  'Pseudoneoponera bispinosa': '双刺修猛蚁',
  'Crematogaster dohrni': '双突柄举腹蚁',
  'Stictoponera bicolor': '双色曲颊猛蚁',
  'Pogonomyrmex bicolor': '双色须蚁',
  'Polyrhachis bihamata': '双钩多刺蚁',
  'Tetramorium bicarinatum': '双隆骨铺道蚁',
  '双脊皱蚁': '双隆骨铺道蚁',
  'Polyrhachis dives': '双齿多刺蚁',
  'Myrmecia varians': '小异牛蚁',
  '多变牛蚁': '小异牛蚁',
  'Camponotus gouldi': '古尔德弓背蚁',
  'Atta cubana': '古巴芭切叶蚁',
  'Aenictus gutianshanensis': '古田山双节行军蚁',
  'Odontomachus goumang': '句芒大齒猛蟻',
  'Sericomyrmex amabilis': '可爱丝切叶蚁',
  'Pheidole jucunda': '可爱大头蚁',
  'Crematogaster pia': '台湾举腹蚁',
  'Aenictus formosensis': '台湾双节行军蚁',
  'Colobopsis taivanae': '台湾平头蚁',
  'Camponotus formosensis': '台湾弓背蚁',
  'Cryptopone taivanae': '臺灣隱針蟻',
  'Pheidole smythiesii': '史氏大头蚁',
  'Polyrhachis lamellidens': '叶形多刺蚁',
  '刺棘蚁': '叶形多刺蚁',
  'Myrmica jessensis': '吉市红蚁',
  'Temnothorax congruus': '和谐切胸蚁',
  'Camponotus dolendus': '哀弓背蚁',
  'Polyrhachis halidayi': '哈氏多刺蚁',
  'Camponotus habereri': '哈氏弓背蚁',
  '臭巨山蚁': '哈氏弓背蚁',
  'Nomamyrmex hartigii': '哈氏漫蚁',
  'Myrmecia haskinsorum': '哈氏牛蚁',
  'Atta colombica': '哥伦比亚芭切叶蚁',
  'Metapone shanyii': '善义后蚁',
  'Messor himalayanus': '喜马拉雅收获蚁',
  'Camponotus quadrinotatus': '四斑弓背蚁',
  'Acromyrmex disciger': '圆盘顶切叶蚁',
  'Aphaenogaster subterranea': '地栖盘腹蚁',
  'Messor aegyptiacus': '埃及收获蚁',
  'Tetraponera aethiops': '埃塞俄比亚细长蚁',
  'Prionopelta aethiopica': '埃塞俄比亚锯猛蚁',
  'Vollenhovia emeryi': '埃氏扁胸切叶蚁',
  'Leptogenys kitteli': '基氏细猛蚁',
  '吉梯细颚蚁': '基氏细猛蚁',
  'Dolichoderus taschenbergi': '塔氏臭蚁',
  'Carebara zengchengensis': '增城盲切叶蚁',
  'Pheidologeton zengchengensis': '增城盲切叶蚁',
  '增城巨首蚁': '增城盲切叶蚁',
  'Atta mexicana': '墨西哥芭切叶蚁',
  'Myrmecocystus mexicanus': '墨西哥蜜罐蚁',
  'Messor variabilis': '多变收获蚁',
  'Cephalotes varians': '分化龟蚁',
  'Tetramorium polymorphum': '多型铺道蚁',
  'Formica polyctena': '多栉蚁',
  'Camponotus punctatissimus': '丝弓背蚁',
  'Myrmecia pilosula': '多毛牛蚁',
  '杰克牛蚁': '多毛牛蚁',
  'Euponera pilosior': '多毛真猛蚁（Euponera pilosior）',
  'Apterostigma pilosum': '多毛翼切叶蚁',
  'Fisheropone pilosior': '多毛真猛蚁（Fisheropone pilosior）',
  'Aphaenogaster geei': '大吉盘腹蚁',
  'Camponotus largiceps': '大头弓背蚁',
  'Messor capitatus': '大头收获蚁',
  'Nothomyrmecia macrops': '大眼响蚁',
  '大眼拟斗牛犬蚁': '大眼响蚁',
  '黎明蚁': '大眼响蚁',
  '恐龙蚁': '大眼响蚁',
  'Adetomyrma clarivida': '大眼无结猛蚁',
  'Aphaenogaster megommata': '大眼盘腹蚁',
  '沙漠大眼盘腹蚁': '大眼盘腹蚁',
  'Syllophopsis magnocula': '大眼脊蚁',
  'Crematogaster osakensis': '大阪举腹蚁',
  'Dilobocondyla fouqueti': '夫氏双凸切叶蚁',
  '北部湾双凸切叶蚁': '夫氏双凸切叶蚁',
  'Pheidole aphrasta': '奇大头蚁',
  'Camponotus mirabilis': '奇异弓背蚁',
  '竹节弓背蚁': '奇异弓背蚁',
  'Camponotus autrani': '奥特朗弓背蚁',
  'Messor capensis': '好望角收获蚁',
  'Rhopalomastix mazu': '媽祖粗跗家蟻',
  'Polyrhachis shixingensis': '始兴多刺蚁',
  'Camponotus wellmani': '威尔曼弓背蚁',
  'Camponotus wellmani gamma': '威尔曼弓背蚁伽马亚种',
  '伽马弓背蚁': '威尔曼弓背蚁伽马亚种',
  'Camponotus wellmani rufipartis': '威尔曼弓背蚁红体亚种',
  'Dorylus wilverthi': '威氏行军蚁',
  'Myrmecia gratiosa': '娇美牛蚁',
  'Messor aralocaspius': '婀娜收获蚁',
  'Camponotus confucii': '孔子弓背蚁',
  '孔氏弓背蚁': '孔子弓背蚁',
  'Leptogenys confucii': '孔子细颚猛蚁',
  'Basiceros singularis': '孤角窝蚁',
  '孤角沟蚁': '孤角窝蚁',
  'Anoplolepis custodiens': '守卫捷蚁',
  'Ectomomyrmex annamitus': '安南扁头猛蚁',
  'Camponotus anningensis': '安宁弓背蚁',
  'Veromessor andrei': '安氏真收获蚁',
  'Pogonomyrmex anzensis': '安沙须蚁',
  'Aphaenogaster famelica': '家盘腹蚁',
  'Pheidole nodus': '宽结大头蚁',
  '菱结大头蚁': '宽结大头蚁',
  'Cataglyphis nodus': '宽节箭蚁',
  'Camponotus pennsylvanicus': '宾州弓背蚁',
  'Camponotus binghamii': '宾氏弓背蚁',
  'Gnamptogenys binghamii': '宾氏曲颊猛蚁',
  'Leptogenys binghamii': '宾氏细颚猛蚁',
  'Myrmoteras binghamii': '宾氏长齿蚁',
  'Pogonomyrmex anergismus': '寄生须蚁',
  'Aenictus fuchuanensis': '富川双节行军蚁',
  'Pheidole antipodum': '对跖大头蚁',
  'Aphaenogaster pumilopuncta': '小刺盘腹蚁',
  '凹唇盘腹蚁': '小刺盘腹蚁',
  'Aenictus minutulus': '小双节行军蚁',
  '微小双节行军蚁': '小双节行军蚁',
  'Colobopsis minus': '小体平头蚁',
  'Messor minor': '小收获蚁',
  'Anochetus subcoecus': '小眼钩猛蚁',
  'Linepithema humile': '小麻臭蚁',
  '阿根廷蚁': '小麻臭蚁',
  'Cephalotes pusillus': '小龟蚁',
  'Camponoyus spanis': '少毛弓背蚁',
  '福建极黑弓背蚁': '少毛弓背蚁',
  'Tetraponera apiculata': '尖细长蚁',
  '尖突细长蚁': '尖细长蚁',
  'Aenictus eugenii': '尤氏盲蚁',
  'Myrmecocystus yuma': '尤马蜜罐蚁',
  'Martialis heureka': '尤里卡火星蚁',
  'Camponotus nicobarensis': '尼科巴弓背蚁',
  'Camponotus nicobarensis monticola': '尼科巴弓背蚁山栖亚种',
  'Odontomachus monticola': '山大齿猛蚁',
  'Dorylus montanus': '山栖行军蚁',
  'Atta insularis': '岛屿芭切叶蚁',
  'Messor structor': '工匠收获蚁',
  'Dinoponera gigantea': '巨人恐猛蚁',
  'Dinomyrmex gigas': '巨人恐蚁',
  '黑腿巨人': '巨人恐蚁',
  'Dinomyrmex gigas borneensis': '巨人恐蚁（婆罗洲亚种）',
  '黄腿巨人': '巨人恐蚁（婆罗洲亚种）',
  'Camponotus capito': '巨头弓背蚁',
  'Solenopsis megergates': '巨工火蚁',
  'Tatuidris tatusia': '巨犰蚁',
  'Megaponera analis': '黄臀巨猛蚁',
  '马塔贝勒蚁': '黄臀巨猛蚁',
  'Tetraponera ophthalmica': '巨眼细长蚁',
  'Odontomachus cephalotes': '巨首大齿猛蚁',
  '头形大齿猛蚁': '巨首大齿猛蚁',
  '宽头陷阱颚蚁': '巨首大齿猛蚁',
  '巨首收获蚁': '巨首收获蚁（肯尼亚收获蚁）',
  'Messor cephalotes': '巨首收获蚁（肯尼亚收获蚁）',
  '肯尼亚收获蚁': '巨首收获蚁（肯尼亚收获蚁）',
  'Myrmecia cephalotes': '巨首牛蚁',
  'Atta cephalotes': '巨首芭切叶蚁',
  'Atta C': '巨首芭切叶蚁',
  'Camponotus parius': '巴瑞弓背蚁',
  'Acropyga butteli': '布氏尖尾蚁',
  'Eciton burchellii': '布氏游蚁',
  '鬼针游蚁': '布氏游蚁',
  'Carebara bruni': '布氏盲切叶蚁',
  'Amoimyrmex bruchi': '布氏祖切叶蚁',
  'Camponotus brutus': '布鲁图斯弓背蚁',
  'Messor hebraeus': '希伯来收获蚁',
  'Zatania cisipa': '希颀蚁',
  'Crematogaster schimmeri': '席氏举腹蚁',
  'Camponotus mitis': '平和弓背蚁',
  'Crematogaster cylindriceps': '柱头举腹蚁',
  'Camponotus nipponicus': '平截弓背蚁',
  'Polyrhachis laevigata': '平滑多刺蚁',
  'Myrmecocystus placodops': '平眼蜜罐蚁',
  'Gaoligongidris planodorsa': '平背高黎贡蚁',
  'Pheidole megacephala': '广大头蚁',
  'Camponotus herculeanus': '广布弓背蚁',
  'Camponotus herculeanus sachalinensis': '广布弓背蚁萨哈林亚种',
  'Ponera guangxiensis': '广西猛蚁',
  'Tetramorium guangxiensis': '广西铺道蚁',
  'Camponotus pompeius': '庞培弓背蚁',
  'Pheidole constanciae': '康斯坦大头蚁',
  'Crematogaster aberrans': '异化举腹蚁',
  'Pheidole dispar': '异大头蚁',
  'Tetraponera dispar': '异细长蚁',
  'Camponotus versicolor': '异色弓背蚁',
  'Pogonomyrmex rugosus bicolor': '异色罗纹须蚁',
  'Tetramorium flinex': '弗氏铺道蚁',
  'Camponotus friedae': '弗里德弓背蚁',
  '大黑巨山蚁': '弗里德弓背蚁',
  'Sphecomyrma freyi': '弗雷氏蜂蚁',
  'Myrmica lobicornis': '弯角红蚁',
  'Messor valentinae': '强壮收获蚁',
  'Camponotus subnitidus': '微亮弓背蚁',
  'Camponotus subnitidus subnitidus': '微亮弓背蚁（指名亚种）',
  'Diacamma caeruleum': '蓝双刺猛蚁',
  'Camponotus subbarbatus': '微须弓背蚁',
  'Messor minusculus（Messor nondentatus）': '微颚齿收获蚁',
  'Dorylus helvolus': '微黄行军蚁',
  'Atta texana': '得州芭切叶蚁',
  'Camponotus whitei': '怀特弓背蚁',
  'Solenopsis fugax': '急逃火蚁',
  'Camponotus luctuosus': '悲痛弓背蚁',
  'Atta goiana': '戈亚斯芭切叶蚁',
  'Messor muticus': '截收获蚁',
  'Solenopsis interrupta': '截火蚁',
  '间断火蚁': '截火蚁',
  'Camponotus mutilarius': '截胸弓背蚁',
  '香斑弓背蚁': '截胸弓背蚁',
  'Camponotus depressiceps': '扁头弓背蚁',
  'Iridomyrmex anceps': '扁平虹臭蚁',
  '双棱虹蚁': '扁平虹臭蚁',
  'Camponotus pseudoirritans': '拟光腹弓背蚁',
  'Camponotus pseudolendus': '拟哀弓背蚁',
  'Cryptopone pseudogigas': '拟大隐猛蚁',
  'Camponotus consobrinus': '拟广布弓背蚁',
  'Myrmecocystus mimicus': '拟态蜜罐蚁',
  '小丑蜜罐蚁': '拟态蜜罐蚁',
  'Mesoponera melanaria': '拟黑中猛蚁',
  'Aenictus paradentatus': '拟齿突双节行军蚁',
  'Formica cunicularia': '掘穴蚁',
  'Pogonomyrmex cunicularius': '穴须蚁',
  'Messor marocanus': '摩洛哥收获蚁',
  'Camponotus satan': '撒旦弓背蚁',
  'Camponotus thadeus': '撒氏弓背蚁',
  '撒迪厄斯弓背蚁': '撒氏弓背蚁',
  'Solenopsis hostilis': '敌火蚁',
  'Camponotus irritabilis': '易怒弓背蚁',
  'Ectomomyrmex astutus': '敏捷扁头猛蚁',
  'Polyergus samura': '斗士悍蚁',
  '佐村悍蚁': '斗士悍蚁',
  'Camponotus dorycus': '新几内亚弓背蚁',
  'Camponotus dorycus recticeps': '新几内亚弓背蚁（矩头亚种）',
  'Dinoponera quadriceps': '方头恐猛蚁',
  'Rossomyrmex quandratinodum': '方结俄蚁',
  'Stictoponera quadrutinodules': '方结凹猛蚁',
  'Messor inermis': '无刺收获蚁',
  'Ochetellus glaber': '无毛凹臭蚁',
  'Brachymyrmex depilis': '无毛短蚁',
  'Camponotus intrepidus': '无畏弓背蚁',
  'Camponotus intrepidus intrepidus': '无畏弓背蚁（指名亚种）',
  '勇敢弓背蚁': '无畏弓背蚁（指名亚种）',
  'Camponotus intrepidus bellicosus': '无畏弓背蚁（好斗亚种）',
  'Tetraponera amargina': '无缘细长蚁',
  'Messor nondentatus': '无颚齿收获蚁',
  'Hypoponera nippona': '日本姬猛蚁',
  'Acropyga nipponensis': '日本尖尾蚁',
  'Camponotus japonicus': '日本弓背蚁',
  'Aphaenogaster japonica': '日本盘腹蚁',
  'Tetramorium nipponense': '日本铺道蚁',
  'Formica japonica': '日本黑褐蚁',
  'Mystrium eques': '显唇迷猛蚁',
  'Myrmecia nobilis': '显贵牛蚁',
  '无翅贵族牛蚁': '显贵牛蚁',
  'Tetraponera notabilis': '显赫细长蚁',
  'Neivamyrmex opacithorax': '暗胸内瓦蚁',
  'Camponotus obscuripes': '暗足弓背蚁',
  'Atta opaciceps': '暗首芭切叶蚁',
  'Stigmatomma mulanae': '木兰点猛蚁',
  '木兰版纳猛蚁': '木兰点猛蚁',
  'Carebara lignata': '木盲切叶蚁',
  'Temnothorax kinomurai': '木野村切胸蚁',
  'Camponotus variegatus': '杂色弓背蚁',
  'Acromyrmex versicolor': '变色顶切叶蚁',
  'Pheidole dugasi': '杜氏大头蚁',
  'Messor striatellus': '条纹收获蚁',
  'Amoimyrmex striatus': '条纹祖切叶蚁',
  'Leptogenys diminuta': '条纹细猛蚁',
  'Protanilla lini': '林氏原細蟻',
  'Colobopsis badia': '栗红平头蚁',
  'Pogonomyrmex badius': '栗红须蚁',
  'Camponotus castaneus': '栗色弓背蚁',
  'Carebara castanea': '栗色盲切叶蚁',
  'Formica glauca': '格劳卡蚁',
  'Anochetus graeffei': '格拉夫钩猛蚁',
  'Liomyrmex gestroi': '格氏润蚁',
  'Messor barbarus santschii': '野蛮收获蚁桑氏亚种',
  'Messor santschii': '野蛮收获蚁桑氏亚种',
  'Polyrhachis illaudata': '梅氏多刺蚁',
  '麦氏棘蚁': '梅氏多刺蚁',
  'Dorylus mayri': '梅氏行军蚁',
  'Pheidole meihuashanensis': '梅花山大头蚁',
  'Solenopsis xyloni': '棉火蚁',
  '棒结近猛蚁': '子弹蚁',
  'Paraponera clavata': '子弹蚁',
  '子弹近猛蚁': '子弹蚁',
  'Crematogaster scutellaris': '棕头举腹蚁',
  'Proformica coriacea*': '棱原蚁',
  'Chrysapace costatus': '棱纹克雷蚁',
  'Tetraponera microcarpa': '榕细长蚁',
  'Cerapachys sulcinodis': '槽结粗角蚁',
  'Odontoponera transversa': '横纹齿猛蚁',
  '横纹齿针蚁': '横纹齿猛蚁',
  'Paraparatrechina sakurae': '樱花拟立毛蚁',
  'Polyergus rufescens': '橘红悍蚁',
  '欧洲亚马逊蚁': '橘红悍蚁',
  'Camponotus decipiens': '欺诈弓背蚁',
  'Aenictus wudangshanensis': '武当山双节行军蚁',
  'Daceton armigerum': '武装毒针蚁',
  'Camponotus ligniperda': '毁木弓背蚁',
  'Crematogaster biroi': '比罗举腹蚁',
  '毕氏举尾蚁': '比罗举腹蚁',
  'Ooceraea biroi': '毕氏卵角蚁',
  'Aenictus bihamatus': '毕氏双节行军蚁（Aenictus bihamatus）',
  'Aenictus biroi': '毕氏双节行军蚁（Aenictus biroi）',
  '比罗双节行军蚁': '毕氏双节行军蚁（Aenictus biroi）',
  'Camponotus bishamon': '毕氏弓背蚁',
  'Formica lugubris': '毛林蚁',
  'Formica villiscapa': '毛柄草地蚁',
  'Amblyopone pilosipetiola': '毛柄钝猛蚁',
  'Meranoplus hirsutus': '毛盾胸切叶蚁',
  'Formica exsecta': '毛眼林蚁',
  '凹头林蚁': '毛眼林蚁',
  'Camponotus piliventris': '毛腹弓背蚁',
  'Camponotus lasiselene': '毛钳弓背蚁',
  'Camponotus jianghuaensis': '江华弓背蚁',
  '污黄拟毛蚁的拉丁学名是 Pseudolasius cibdelus\n\n（注：在部分资料中，其学名也被拼写为 Pseudolasius cibdetus。）': '污黄拟毛蚁',
  '拟毛蚁': '污黄拟毛蚁',
  'Atta vollenweideri': '沃伦魏德芭切叶蚁(直译)',
  '沃氏芭切叶蚁': '沃伦魏德芭切叶蚁(直译)',
  'Camponotus wasmanni': '沃斯曼弓背蚁',
  'Pheidole watsoni': '沃森大头蚁',
  'Messor wasmanni': '沃氏收获蚁',
  'Leptanilla voldemort': '沃达细蚁（伏地魔细蚁）',
  '伏地魔细蚁': '沃达细蚁（伏地魔细蚁）',
  'Aenictus shuckardi': '沙克德双节行军蚁',
  '舒氏行军蚁': '沙克德双节行军蚁',
  'Camponotus arenatus': '沙地弓背蚁',
  '沙漠弓背蚁': '沙地弓背蚁',
  'Messor arenarius': '沙地收获蚁',
  'Camponotus atrox': '沟齿弓背蚁',
  '韩国红胸蚁': '沟齿弓背蚁',
  '韩国红胸弓背蚁': '沟齿弓背蚁',
  'Messor galla': '没食子收获蚁',
  'Aenictus henanensis': '河南双节行军蚁',
  'Monomorium pharaonis': '法老小家蚁',
  '法老蚁': '法老小家蚁',
  '小黄家蚁': '法老小家蚁',
  'Aenictus thailandianus': '泰国盲蚁',
  'Dorylus titan': '泰坦行军蚁',
  'Dorylus titan vinalli': '泰坦行军蚁维氏亚种',
  'Camponotus loweryi': '洛厄里弓背蚁',
  'Anochetus troglodytes': '洞居盲细钩猛蚁',
  'Tetramorium tsushimae': '津岛铺道蚁',
  'Camponotus albivillosus': '浅毛弓背蚁',
  'Acropyga oceanica': '海洋尖尾蚁',
  'Cataglyphis pallida': '淡色箭蚁',
  '透明箭蚁': '淡色箭蚁',
  'Pheidole flaveria': '淡黄大头蚁',
  'Camponotus aterrimus': '深黑弓背蚁',
  'Camponotus confusus': '混乱弓背蚁',
  'Camponotus misturus': '混杂弓背蚁',
  'Anochetus mixtus': '混杂钩猛蚁',
  'Crematogaster vagula': '游举腹蚁',
  'Plagiolepis manczshurica': '满斜结蚁',
  '满洲斜结蚁': '满斜结蚁',
  'Camponotus suffusus': '满茸弓背蚁',
  'Camponotus suffusus suffusus': '满茸弓背蚁（指名亚种）',
  'Camponotus suffusus bendigensis': '满茸弓背蚁（本迪戈亚种）',
  'Myrmecia flammicollis': '火山牛蚁',
  'Formica cinerea': '灰褐蚁',
  'Cardiocondyla obscurior': '灰黑心结蚁',
  'Acropyga acutiventris': '灵动尖尾蚁',
  'Messor tropicorum': '热带收获蚁',
  'Solenopsis geminata': '热带火蚁',
  'Camponotus ustus': '燃弓背蚁',
  'Crematogaster anthracina': '煤黑举腹蚁',
  'Gnamptogenys panda': '熊猫曲颊猛蚁',
  '四川曲颊猛蚁': '熊猫曲颊猛蚁',
  'Myrmecia urens': '燃烧牛蚁',
  'Colobopsis explodens': '爆炸平头蚁',
  'Aenictus javanus': '爪哇双节行军蚁',
  'Ectomomyrmex javanus': '爪哇扁头猛蚁',
  'Ectomomyrmex lobocarenus': '片突扁头猛蚁',
  'Ponera pianmana': '片马猛蚁',
  'Messor bucephalus': '牛头收获蚁',
  'Tetraponera buops': '牛眼细长蚁',
  '布氏细长蚁': '牛眼细长蚁',
  'Messor bouvieri': '牧氏收获蚁',
  'Tetraponera attenuata': '狭唇细长蚁',
  'Harpegnathos venator': '猎镰猛蚁',
  'Camponotus molossus': '獒弓背蚁',
  '莫罗索思弓背蚁': '獒弓背蚁',
  'Aphaenogaster xuantian': '玄天盘腹蚁',
  'Lasius alienus': '玉米毛蚁',
  'Messor regalis': '王者收获蚁',
  'Crematogaster matsumurai': '玛氏举腹蚁',
  'Atta bisphaerica': '球形芭切叶蚁',
  'Solenopsis electra': '琥珀火蚁',
  'Camponotus vitiosus': '瑕疵弓背蚁',
  '东京弓背蚁': '瑕疵弓背蚁',
  '东京巨山蚁': '瑕疵弓背蚁',
  'Pheidole rhea': '瑞亚大头蚁',
  'Camponotus ager': '田野弓背蚁',
  'Temnothorax ambiguus': '疑切胸蚁',
  'Cataglyphis cursor': '疾行箭蚁',
  'Strongylognathus tylonus': '瘤点圆颚蚁',
  '瘤点圆颚切叶蚁': '瘤点圆颚蚁',
  'Novomessor albisetosus': '白毛新收获蚁',
  'Aphaenogaster senilis': '白毛盘腹蚁',
  '灰老盘腹蚁': '白毛盘腹蚁',
  'Camponotus albocinctus': '白环弓背蚁',
  'Technomyrmex albipes': '白足狡臭蚁',
  'Camponotus bedoti': '百陶弓背蚁',
  'Camponotus devestivus': '的威弓背蚁',
  '饴色大蚁': '的威弓背蚁',
  '褪色弓背蚁': '的威弓背蚁',
  'Acromyrmex coronatus': '冠顶切叶蚁',
  'Aenictus piercei': '皮氏双节行军蚁',
  'Pheidole pieli': '皮氏大头蚁',
  'Streblognathus peetersi': '皮氏粗颚猛蚁',
  '皮特斯纹胸猛蚁': '皮氏粗颚猛蚁',
  'Pheidole gatesi': '盖氏大头蚁',
  'Pseudolasius similus': '相似拟光蚁',
  'Tetramorium simillimum': '相似铺道蚁',
  'Cephalotes clypeatus': '盾龟蚁',
  'Acanthognathus ocellatus': '眼棘颚蚁',
  'Messor picturatus': '着色收获蚁',
  'Solenopsis tipuna': '知本火蚁',
  'Pristomyrmex brevispinosus': '短刺棱胸切叶蚁',
  'Pachycondyla breviscapa': '短柄厚结蚁',
  'Camponotus breviscapus': '短柄弓背蚁',
  'Myrmecia brevinoda': '短结牛蚁',
  'Brachyponera brevidorsa': '短背短猛蚁',
  'Acanthognathus brevicornis': '短角棘颚蚁',
  'Camponotus brevicollis': '短颈弓背蚁',
  'Pheidole parva': '矮大头蚁',
  'Formica yessensis': '石狩红蚁',
  'Messor testaceus': '砖红收获蚁',
  'Gigantiops destructor': '破坏巨眼蚁',
  'Ponera shennong': '神农猛蚁',
  '神農針蟻': '神农猛蚁',
  'Camponotus sanctus': '神圣弓背蚁',
  'Myrmecocystus colei': '科尔蜜罐蚁',
  'Novomessor cockerelli': '科氏新收获蚁',
  'Dorylus kohli': '科氏行军蚁',
  'Messor excursionis': '移动收获蚁',
  'Odontomachus troglodytes': '穴居大齿猛蚁',
  'Camponotus turkestanicus': '突厥弓背蚁',
  'Aenictus artipus': '窄足双节行军蚁',
  '窄颈弓背蚁': '窄颈弓背蚁（窄径）',
  'Camponotus angusticollis': '窄颈弓背蚁（窄径）',
  'Messor erectus': '立毛收获蚁',
  'Labidus praedator': '笼罩钳蚁',
  'Amblyopone michaelseni': '米氏钝猛蚁',
  'Myrmica mifui': '米芾红蚁',
  'Cataulacus granulatus': '粒沟切叶蚁',
  'Odontomachus granatus': '粒纹大齿猛蚁',
  'Anochetus rugosus': '粗糙钩猛蚁',
  '粗钩猛蚁': '粗糙钩猛蚁',
  'Crematogaster artifex': '粗纹举腹蚁',
  'Pachycondyla crassinoda': '粗结厚结猛蚁',
  'Messor perantennatus': '粗节收获蚁',
  'Aenictus pachycerus': '粗角双节行军蚁',
  'Camponotus somalinus': '索马里弓背蚁',
  'Iridomyrmex purpureus': '紫彩虹臭蚁',
  'Diacamma viridipurpureum': '紫青双刺猛蚁',
  'Camponotus singularis': '红头弓背蚁',
  'Camponotus singularis rufomaculatus': '红头弓背蚁（红斑亚种）',
  'Formica truncorum': '叶盛山蚁',
  'Camponotus rufus': '红弓背蚁',
  'Manica rubida': '红狂蚁',
  'Myopopone castanea': '红矛猛蚁',
  'Camponotus rufoglaucus': '红缘弓背蚁',
  'Camponotus rufifemur': '红股弓背蚁',
  '红胡须蚁': '红胡须蚁（巴巴特斯）',
  'Pogonomyrmex barbatus': '红胡须蚁（巴巴特斯）',
  '巴巴特斯石竹蚁': '红胡须蚁（巴巴特斯）',
  'Messor minor hesperius': '红胸收获蚁',
  'Polyrhachis rubigastrica': '红腹多刺蚁',
  'Messor rufotestaceus': '红褐收获蚁',
  'Formica rufa': '红褐林蚁',
  'Pseudoneoponera rufipes': '红足修猛蚁',
  'Camponotus rufipes': '红足弓背蚁',
  'Formica rufibarbis': '红须蚁',
  'Tetraponera rufonigra': '红黑细长蚁',
  'Iridomyrmex rufoniger': '红黑虹臭蚁',
  'Camponotus johnclarki': '约翰克拉克弓背蚁',
  'Messor incorruptus': '纯洁收获蚁',
  'Messor striatifrons': '纹额收获蚁',
  'Camponotus novaeboracensis': '纽约弓背蚁',
  'Pogonomyrmex tenuispinus': '细刺须蚁',
  'Meranoplus tenuiscultus': '细刻瘤胸切叶蚁',
  'Monomorium destructor': '破坏单家蚁',
  'Anoplolepis gracilipes': '长足捷蚁',
  '长脚捷蚁': '长足捷蚁',
  'Polyrhachis rastellata': '结多刺蚁',
  '统领弓背蚁': '统领弓背蚁（统领蚁）',
  'Camponotus magister': '统领弓背蚁（统领蚁）',
  'Camponotus sericeus': '绢毛弓背蚁',
  'Iridomyrmex victorianus': '维多利亚虹臭蚁',
  'Dorylus vishnui': '维希努行军蚁',
  'Leptogenys birmana': '缅甸细颚猛蚁',
  'Camponoyus vanispinus': '缺刺弓背蚁',
  'Acromyrmex rugosus': '罗格斯顶切叶蚁',
  '皱切叶蚁': '罗格斯顶切叶蚁',
  'Tetramorium wroughtonii': '罗氏铺道蚁',
  'Pogonomyrmex rugosus': '罗纹须蚁',
  'Camponotus pulcher': '美丽弓背蚁',
  'Myrmecia callima': '美丽牛蚁',
  'Camponotus americanus': '美国弓背蚁',
  'Aphaenogaster occidentalis': '美西盘腹蚁',
  'Camponotus pudorosus': '羞怯弓背蚁',
  'Atopomyrmex calpocalycola': '翁萼豆异形蚁',
  'Carebara diversa laotina': '老挝盲切叶蚁',
  '全异盲切叶蚁老挝亚种': '老挝盲切叶蚁',
  'Diacamma rugosum': '聚纹双刺猛蚁',
  'Myrmecocystus kennedyi': '肯氏蜜罐蚁',
  'Polyrhachis hookeri': '胡克多刺蚁',
  'Camponotus fragilis': '脆弱弓背蚁',
  'Pheidole tumida': '膨胀大头蚁',
  'Camponotus inflatus': '膨胀弓背蚁',
  'Camponotus aethiops': '艾提弓背蚁',
  'Nomamyrmex esenbeckii': '艾氏漫蚁',
  'Cataglyphis aenescens': '艾箭蚁',
  'Monomorium floricola': '花居小家蚁',
  'solenopsis soochowensis': '苏州火蚁',
  'Odontomachus procerus': '高大齿猛蚁',
  'Tetramorium lanuginosum': '茸毛铺道蚁',
  '绒毛皱家蚁': '茸毛铺道蚁',
  'Proformica epinotalis': '草原原蚁',
  'Formica pratensis': '草原蚁',
  'Tetramorium caespitum': '草地铺道蚁',
  '荒漠收获蚁': '白刺收获蚁',
  'Messor desertus': '白刺收获蚁',
  'Camponotus storeatus': '存储弓背蚁',
  '苍绒弓背蚁': '存储弓背蚁',
  'Pheidole morrisii': '莫氏大头蚁',
  '莫里斯大头蚁': '莫氏大头蚁',
  'Atopomyrmex mocquerysi': '莫氏异形蚁',
  'Technomyrmex modiglianii': '莫氏狡臭蚁',
  'Colobopsis leonardi': '来氏平头蚁',
  'Camponotus lespesii': '莱氏弓背蚁',
  'Aenictus philippinensis': '菲律宾双节行军蚁',
  'Atta saltensis': '萨尔塔芭切叶蚁',
  'Messor lusitanicus': '葡萄牙收获蚁',
  'Proformica mongolica': '蒙古原蚁',
  '中华蜜罐蚁': '蒙古原蚁',
  'Iridomyrmex lividus': '蓝彩虹臭蚁',
  'Leptogenys cyanicatena': '蓝链细颚猛蚁',
  'Odontomachus formosae': '蓬莱大齿猛蚁',
  'Lasius aphidicola': '蚜居毛蚁',
  'Camponotus cruentatus': '血斑弓背蚁',
  'Formica sanguinea': '血红林蚁',
  'Iridomyrmex sanguineus': '血色虹臭蚁',
  'Cardiocondyla nuda': '裸心结蚁',
  'Camponotus fuscivillosus': '褐毛弓背蚁',
  'Camponotus semirufus': '褐红弓背蚁',
  '小突厥，缺刺弓背蚁': '褐红弓背蚁',
  'Stigmatomma rubiginoum': '褐红点猛蚁',
  'Myrmecia fulviculis': '褐臀牛蚁',
  'Myrmicaria brunnea': '褐色脊红蚁',
  'Myrmecia fulvipes': '褐足牛蚁',
  'Dolichoderus sibiricus': '西伯利亚臭蚁',
  'Camponotus siemsseni': '西姆森弓背蚁',
  '希氏巨山蚁': '西姆森弓背蚁',
  'Aenictus silvestrii': '西氏双节行军蚁',
  '韦氏行军蚁': '西氏双节行军蚁',
  'Odontomachus silvestrii': '西氏大齿猛蚁',
  'Stigmatomma silvestrii': '西氏点猛蚁',
  'Amoimyrmex silvestrii': '西氏祖切叶蚁',
  '西氏顶切叶蚁': '西氏祖切叶蚁',
  'Acromyrmex silvestrii': '西氏祖切叶蚁',
  'Aneuretus simoni': '西蒙原臭蚁',
  'Camponotus cornis': '角弓背蚁',
  'Messor angularis': '角收获蚁',
  'Aenictus shilintongae': '诗琳通双节行军蚁',
  'Myrmecocystus': '谎言蜜罐蚁',
  'Camponotus circumspectus': '谨慎弓背蚁',
  'Gesomyrmex howardi': '豪氏短角蚁',
  'Stigmatomma bellii': '贝利点猛蚁',
  'Pseudomyrmex beccarii': '贝卡伪切叶蚁',
  'Aphaenogaster beccarii': '贝卡盘腹蚁',
  '贝卡氏盘腹蚁': '贝卡盘腹蚁',
  'Camponotus batesii': '贝氏弓背蚁',
  'Eciton rapax': '贪婪游蚁',
  'Myrmecia gulosa': '贪食牛蚁',
  'Camponotus fellah': '费拉弓背蚁',
  '费里德弓背蚁': '费拉弓背蚁',
  'Centromyrmex feae': '费氏中盲猛蚁',
  '费氏弓背蚁': '费氏弓背蚁（黑金弓背蚁）',
  'Camponotus fedtschenkoi': '费氏弓背蚁（黑金弓背蚁）',
  '黑金弓背蚁': '费氏弓背蚁（黑金弓背蚁）',
  '黑斑弓背蚁': '费氏弓背蚁（黑金弓背蚁）',
  'Messor ferreri': '费氏收获蚁',
  'Aphaenogaster feae': '费氏盘腹蚁',
  'Proformica jacoti': '贾氏原蚁',
  'Solenopsis jacoti': '贾氏火蚁',
  'Aenictus sagei': '赛奇双节行军蚁',
  'Harpegnathos saltator': '跳镰猛蚁',
  'Messor instabilis': '躁动收获蚁',
  'Camponotus radiatus': '辐毛弓背蚁',
  'Camponotus festinus': '迅捷弓背蚁',
  'Camponotus festinus inezae': '迅捷弓背蚁（伊内兹亚种）',
  'Camponotus festinus diligens': '迅捷弓背蚁（勤奋亚种）',
  'Camponotus festinus festinus': '迅捷弓背蚁（指名亚种）',
  'Cataglyphis velox': '迅捷箭蚁',
  'Temnothorax affinis': '近缘切胸蚁',
  'Carebara affinis': '近缘盲切叶蚁',
  'Camponotus parabarbatus': '近须弓背蚁',
  'Buniapone amblyops': '迟钝匿猛蚁',
  'Messor decipiens': '迷惑收获蚁',
  'Myrmecia aberrans': '迷走牛蚁',
  'Xymmer phungi': '逢股猛蚁',
  'Lasius umbratus': '遮盖毛蚁',
  'Camponotus banghaasi': '邦哈斯弓背蚁',
  'Hypoponera sauteri': '邵氏姬針蟻',
  'Acropyga sauteri': '邵氏尖尾蚁',
  'Ectomomyrmex sauteri': '邵氏扁头猛蚁',
  'Discothyrea sauteri': '邵氏无齿猛蚁',
  'Carebara sauteri': '邵氏寡家蟻',
  'Cryptopone sauteri': '邵氏隐猛蚁',
  'Dolichoderus affinis': '邻臭蚁',
  'Dorylus affinis': '邻行军蚁',
  'Messor vicinus': '邻近收获蚁',
  'Aenictus zhengi': '郑氏双节行军蚁',
  'Ectomomyrmex zhengi': '郑氏扁头猛蚁',
  'Camponotus cacicus': '酋长弓背蚁',
  'Camponotus reichardti': '里氏弓背蚁',
  'Anochetus risii': '里氏钩猛蚁',
  'Camponotus barbaricus': '野蛮弓背蚁',
  '野蛮收获蚁': '野蛮收获蚁（原生收获蚁）',
  'Messor barbarus': '野蛮收获蚁（原生收获蚁）',
  '原生收获蚁': '野蛮收获蚁（原生收获蚁）',
  '芭芭拉收获蚁': '野蛮收获蚁（原生收获蚁）',
  'Messor barbarus gallaoides': '野蛮收获蚁（五倍子亚种）',
  'Allomerus auropunctatus': '金刻异节蚁',
  '金刻沃氏蚁': '金刻异节蚁',
  'Wasmannia auropunctata': '金刻异节蚁',
  '小火蚁': '金刻异节蚁',
  'Solenopsis metallica': '金属火蚁',
  '金属皱猛蚁': '金属皱突蚁（金属蚁）',
  'Rhytidoponera metallica': '金属皱突蚁（金属蚁）',
  'Camponotus tonkinus': '金毛弓背蚁',
  'Camponotus detritus': '金沙弓背蚁',
  'Camponotus aurocinctus': '金环弓背蚁',
  'Camponotus auriventris': '金腹弓背蚁',
  'Messor aciculatus': '针毛收获蚁',
  'Eciton hamatum': '钩齿游蚁',
  'Camponotus aeneopilosus': '铜毛弓背蚁',
  'Iridomyrmex viridiaeneus': '铜绿虹臭蚁',
  '银丝箭蚁': '银丝箭蚁（银丝蚁）',
  'Cataglyphis bombycina': '银丝箭蚁（银丝蚁）',
  'Camponotus chromaiodes': '锈色弓背蚁',
  '木匠蚁': '锈色弓背蚁',
  'Paratopula ceylonica': '锡兰华丽蚁',
  'Aenictus ceylonicus': '锡兰双节行军蚁',
  'Camponotus longiceps': '长头弓背蚁',
  'Aphaenogaster longiceps': '长头盘腹蚁',
  '漏斗蚁': '长头盘腹蚁',
  'Probolomyrmex longiscapus': '长柄小盲猛蚁',
  'Camponotus nipponensis': '长毛弓背蚁',
  'Strumigenys exilirhina': '长瘤颚蚁',
  'Aenictus longinodus': '长结双节行军蚁',
  'Oecophylla longinoda': '长结织叶蚁',
  'Paratrechina longicornis': '长角立毛蚁',
  'Dinoponera longipes': '长足恐猛蚁',
  'Amblyopone longidens': '长颚钝猛蚁',
  'Pheidole allani': '阿伦大头蚁',
  'Pseudoatta argentina': '阿根廷拟芭切叶蚁',
  '阿根廷伪芭切叶蚁': '阿根廷拟芭切叶蚁',
  '拟芭寄生切叶蚁': '阿根廷拟芭切叶蚁',
  'Polyrhachis armata': '阿玛多刺蚁',
  'Polyrhachis armata defensa': '阿玛多刺蚁 防御亚种',
  'Plagiolepis alluaudi': '阿禄斜结蚁',
  'Camponotus ashokai': '阿育王弓背蚁',
  'Tetramorium shensiense': '陕西铺道蚁',
  'Aphaenogaster gibbosa': '隆胸盘腹蚁',
  'Strumigenys kumadori': '隈取瘤颚蚁',
  'Opamyrma hungvuong': '雄王穴细蚁',
  'Aphaenogaster exasperata': '雕刻盘腹蚁',
  'Acropyga yushi': '雨师尖尾蚁',
  'Camponotus niveosetosus': '多毛弓背蚁',
  '白发弓背蚁': '多毛弓背蚁',
  'Aenictus hodgsoni': '霍氏双节行军蚁',
  'Camponotus egregius': '非凡弓背蚁',
  'Dorylus gribodoi': '非洲行军蚁',
  '非洲矛蚁': '非洲行军蚁',
  'Carebara vidua': '非洲贼蚁',
  'Camponotus ephippium': '鞍弓背蚁',
  'Aenictus weissi': '韦氏行军蚁（韦氏双节行军蚁）',
  'Camponotus barbatus': '须弓背蚁',
  'Camponotus barbosus': '人厌弓背蚁',
  'Messor rugosus': '须收获蚁',
  'Tetraponera allaborans': '飘细长蚁',
  'Tetramorium inquilinum': '食客铺道蚁',
  'Myrmecia esuriens': '饕餮牛蚁',
  '斗牛犬蚁': '饕餮牛蚁',
  '公牛蚁': '饕餮牛蚁',
  'Brachyponera sennaarensis': '马拉维短猛蚁',
  'Anochetus madaraszi': '马达拉钩猛蚁',
  'Pogonomyrmex maricopa': '马里科帕须蚁',
  'Camponotus camelinus': '驼色弓背蚁',
  'Strumigenys takasago': '高作瘤颚蚁',
  'Aphaenogaster takahashii': '高桥盘腹蚁',
  'Euprenolepis procera': '高真结蚁',
  'Carebara altinodus': '高结盲切叶蚁',
  'Messor mcarthuri': '麦氏收获蚁',
  'Camponotus gilviceps': '黄头弓背蚁',
  'Myrmecia apicalis': '黄尾牛蚁',
  'Camponotus albosparsus': '黄斑弓背蚁',
  'Camponotus auratiacus': '黄毛弓背蚁',
  'Lasius flavus': '黄毛蚁',
  'Oecophylla smaragdina': '黄猄蚁',
  '翠绿织叶蚁（拉丁名直译）': '黄猄蚁',
  '绿树蚁': '黄猄蚁',
  'Brachyponera lutea': '黄短猛蚁',
  '琵琶短猛蚁': '黄短猛蚁',
  'Camponotus helvus': '黄腹弓背蚁',
  'Dorylus fulvus': '黄色行军蚁',
  'Nylanderia flavipes': '黄足尼氏蚁',
  'Brachyponera luteipes': '黄足短猛蚁',
  'Myrmecia tarsata': '黄跗牛蚁',
  'Camponotus nigriceps': '黑头弓背蚁',
  'Myrmecia nigriceps': '黑头牛蚁',
  'Tapinoma melanocephalum': '黑头酸臭蚁',
  'Myrmecia nigrocincta': '黑带牛蚁',
  'Myrmecia nigriscapa': '黑柄牛蚁',
  'Myrmecia pyriformis': '梨形牛蚁',
  'Lasius niger': '黑毛蚁',
  'Carebara melasolena': '黑沟盲切叶蚁',
  'Messor ponticus': '黑海收获蚁',
  'Solenopsis richteri': '黑火蚁',
  '里氏火蚁': '黑火蚁',
  'Cephalotes atratu': '黑盾龟蚁',
  'Tetraponera nigra': '黑细长蚁',
  'Monomorium intrudens': '黑腹小家蚁',
  '入侵单家蚁': '黑腹小家蚁',
  'Brachyponera nigrita': '黑色短猛蚁',
  'Dorylus nigricans': '黑色行军蚁',
  'Cephalotes atratus': '黑衣龟蚁',
  'Crematogaster rogenhoferi': '黑褐举腹蚁',
  'Monomorium ergatogyna': '勤劳小家蚁',
  'Camponotus nigricans': '黑角弓背蚁',
  'Camponotus mus': '鼠弓背蚁',
  'Aenictus dentatus': '齿突双节行军蚁',
  'Messor denticornis': '齿节收获蚁',
  'Paltothyreus tarsatus': '齿跗枪盾猛蚁',
  'Plagiolepis longwang': '龙王斜结蚁',
  'Carebara diversa draco': '龙盲切叶蚁',
};

const importedSpeciesDisambiguation = <String, String>{
  'SP17牛蚁（未定种）': 'Myrmecia sp.17',
  '丝腹弓背蚁（君王亚种）': 'Camponotus sericeiventris rex',
  '丝腹弓背蚁指名亚种': 'Camponotus sericeiventris sericeiventris',
  '凶猛弓背蚁': 'Camponotus rapax',
  '双齿多刺蚁': 'Polyrhachis dives',
  '四斑弓背蚁': 'Camponotus quadrinotatus',
  '大眼响蚁': 'Nothomyrmecia macrops',
  '宾氏长齿蚁': 'Myrmoteras binghamii',
  '微颚齿收获蚁': 'Messor minusculus（Messor nondentatus）',
  '易怒弓背蚁': 'Camponotus irritabilis',
  '无毛凹臭蚁': 'Ochetellus glaber',
  '无毛短蚁': 'Brachymyrmex depilis',
  '无颚齿收获蚁': 'Messor nondentatus',
  '满茸弓背蚁（指名亚种）': 'Camponotus suffusus suffusus',
  '满茸弓背蚁（本迪戈亚种）': 'Camponotus suffusus bendigensis',
  '非洲行军蚁': 'Dorylus gribodoi',
  '黄斑弓背蚁': 'Camponotus albosparsus',
  '黑色行军蚁': 'Dorylus nigricans',
  '拟黑多刺蚁': '学名待核对',
};
